/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 04:49:32 PM CDT 
//

package com.dell.isg.smi.service.server.configuration.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dell.isg.smi.service.server.configuration.model.test
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.isg.smi.service.server.configuration.model.test
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link SystemConfiguration }
     * 
     */
    public SystemConfiguration createSystemConfiguration() {
        return new SystemConfiguration();
    }


    /**
     * Create an instance of {@link SystemConfiguration.Component }
     * 
     */
    public ServerComponent createSystemConfigurationComponent() {
        return new ServerComponent();
    }


    /**
     * Create an instance of {@link SystemConfiguration.Component.SubComponent }
     * 
     */
    public SubComponent createSubComponent() {
        return new SubComponent();
    }


    /**
     * Create an instance of {@link SystemConfiguration.Component.InnerComponent.NestedComponent }
     * 
     */
    public NestedComponent createSystemConfigurationNestedComponent() {
        return new NestedComponent();
    }


    /**
     * Create an instance of {@link SystemConfiguration.Component.Attribute }
     * 
     */
    public Attribute createSystemConfigurationComponentAttribute() {
        return new Attribute();
    }


    /**
     * Create an instance of {@link SystemConfiguration.Component.InnerComponent.Attribute }
     * 
     */
    public Attribute createSubComponentAttribute() {
        return new Attribute();
    }


    /**
     * Create an instance of {@link NestedComponent.Attribute }
     * 
     */
    public Attribute createNestedComponentAttribute() {
        return new Attribute();
    }

}
